name: Laravel CI/CD Pipeline

# Run the pipeline on any push or pull request to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up PHP and Composer
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install dependencies
        run: composer install

      # Step 3: Run Laravel tests (Optional - Laravel has built-in tests, but this example doesn't use them)
      - name: Run tests
        run: php artisan test

      # Step 4: Set up Docker and build the image
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 5: Build and push the Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: your_dockerhub_username/laravel-welcome-app:latest

      # Step 6: (Optional) Deploy the Docker container to a server or service if needed
